# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 MASH project contributors
# SPDX-FileCopyrightText: 2023-2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Fail if required Sable settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "item.when | bool and lookup('vars', item.name, default='') | string | length == 0"
  with_items:
    - { "name": "sable_uid", when: true }
    - { "name": "sable_gid", when: true }
    - { "name": "sable_hostname", when: true }
    - { "name": "sable_path_prefix", when: true }
    - { "name": "sable_container_network", when: true }
    - { "name": "sable_default_hs_url", when: true }
    - { "name": "sable_container_labels_traefik_compression_middleware_name", when: "{{ sable_container_labels_traefik_compression_middleware_enabled }}" }

- name: Run if Traefik is enabled
  when: sable_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for Sable are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - sable_container_labels_traefik_hostname
        - sable_container_labels_traefik_path_prefix

    - name: Fail if sable_container_labels_traefik_path_prefix is different than /
      ansible.builtin.fail:
        msg: >-
          sable_container_labels_traefik_path_prefix (`{{ sable_container_labels_traefik_path_prefix }}`) must be `/`.
          Sable does not support hosting under a subpath yet.
      when: "sable_container_labels_traefik_path_prefix != '/'"

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `sable_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if sable_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          sable_container_labels_traefik_path_prefix (`{{ sable_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/sable`).
      when: "sable_container_labels_traefik_path_prefix != '/' and sable_container_labels_traefik_path_prefix[-1] == '/'"
